// Code generated by MockGen. DO NOT EDIT.
// Source: ../testdemo/mockkkk/servie.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDB is a mock of DB interface
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Hii mocks base method
func (m *MockDB) Hii() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hii")
	ret0, _ := ret[0].(string)
	return ret0
}

// Hii indicates an expected call of Hii
func (mr *MockDBMockRecorder) Hii() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hii", reflect.TypeOf((*MockDB)(nil).Hii))
}
